services:
  mi-app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_foodix?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=foodix_admin
      - SPRING_DATASOURCE_PASSWORD=OtraPasswordSegura456!@#
      - APP_UPLOAD_DIR=uploads
      
      # Email configuration
      - SPRING_MAIL_USERNAME=sistemafoodix@gmail.com
      - SPRING_MAIL_PASSWORD=spdtspyvzwczljgz
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=smtp.gmail.com
      
      - SPRING_PROFILES_ACTIVE=dev
      - LOGGING_LEVEL_COM_EXAMPLE=DEBUG
      - API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1NTksImV4cCI6MTc2MzMxODEzNH0.bzVljvbLILWrSrhsLV8sI7c-6I1gw7URf6R0lV0lToU
    volumes:
      - app-uploads:/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=db_foodix
      - MYSQL_ROOT_PASSWORD=MiPasswordSuperSeguro123!@#
      - MYSQL_USER=foodix_admin
      - MYSQL_PASSWORD=OtraPasswordSegura456!@#
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMiPasswordSuperSeguro123!@#"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  app-uploads: